default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch('DATABASE_HOST') { 'db' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'postgres' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { 'whatsapp_db' } %>

test:
  <<: *default
  database: whatsapp_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_PROD") { 'whatsapp_db' } %>
